team-telnyx/telnyx-webrtc-android

- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Peer.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/SocketMethod.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/utilities/ConnectivityHelper.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/ParamRequest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/CallTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/PeerTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/socket/TxSocketTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/utilities/ConnectivityHelperTest.kt
[WebRTC-548- Added dtmf support.](https://telnyx.atlassian.net/browse/WEBRTC-548)
---
Added a dtmf() method that will send DTMF tone to an ongoing call. 
Also created IS_TESTING build configuration which we use during tests. This temporarily disables BugSnag so that we don't get false bugs reported when we are intentionally testing failures. 
No way of sending DTMF
DTMF can now be sent via the dtmf() method
1. Create an ongoing call to +13129457420
2. Use the dtmfPressed() method durinc call with an alphanumeric character ("2") - I temporarily fired this method when onHold is pressed to test. 
3. See response in logs.
> [WEBRTC-548] Added dtmf support

- README.md
Signed-off-by: Lucas Pais <lucasp@7g804d3.office.telnyx.com>
[WEBRTC-579 - [Android] App does not work when enabling obfuscation flags on build.gradle file.](https://telnyx.atlassian.net/browse/WEBRTC-579)
---
We found an issue with connecting to websocket and placing call, whenever proguard rules are modified by adding
```gradle
buildTypes {
release {
minifyEnabled true
shrinkResources true
...
}
debug {
minifyEnabled true
shrinkResources true
...
}
}
```
causing the following error:
```logs
2021-06-08 10:48:12.102 13951-14084/com.telnyx.webrtc.sdk D/VERTO: Connection established
2021-06-08 10:48:12.102 13951-14084/com.telnyx.webrtc.sdk D/VERTO: [a] Sending [{}]
2021-06-08 10:48:12.404 13951-14084/com.telnyx.webrtc.sdk D/VERTO: [a] Receiving …
```
> [WEBRTC-579] Add ProGuard workarround to README.md file

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/SocketMethod.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocketListener.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/socket/TxSocketTest.kt
[WebRTC-619 - Add telnyx session ID and leg ID to Call object.](https://telnyx.atlassian.net/browse/WEBRTC-619)
---
The private variables telnyxSessionId and telnyxLegId are now set within the call object whenever a ringing or offer received listener method is fired. 
These are then accessible via getter methods. 
No access to telnyxSessionId or telnyxLegId. Neither variables were available or set.
telnyxSessionId and telnyxLegId are set within the call object via listener methods, these are then accessible via getter methods. There is a possibility of these returning null if they are not yet set. 
1. Create an invite or receive a call and monitor the telnyxSessionId or telnyxLegId variables within Call.kt. These are now set appropriately.
> [WEBRTC-619] Add telnyx session ID and leg ID to Call object

- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/utilities/ConnectivityHelper.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/socket/TxSocketTest.kt
[WebRTC-623 - Improve logging.](https://telnyx.atlassian.net/browse/WEBRTC-623)
---
This PR adds a boolean value isConnected, which switches to true once a connection is established in the TxSocket class. If this is set to false, no message will be sent on the socket and a log is provided
This PR also adds required changes to TxSocket tests that should have been done earlier in relation to BugSnag. 
No check, users had to rely on the onConnectionEstablished callback. 
Now, in addition to the onConnectionEstablished callback, there is also a log that fires whenever somebody attempts to send a message on TxSocket that has no connection. 
1. Launch the application and attempt an action before a connection is established
2. Monitor logs for a message
3. Launch the application, connect, and …
> [WEBRTC-623] Add connection check + Log, before sending message on socket

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-636 - per call token authentication investigation.](https://telnyx.atlassian.net/browse/WEBRTC-636)
---
Remove build config check before planting timber logging tree.
Build check before planting tree
plant tree regardless of build config
> [WEBRTC-636] Remove BuildConfig check when setting log level

- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/DialogParams.kt
[WebRTC-640 -  Set an SDK property on INVITE (include client type and version in user-agent field).](https://telnyx.atlassian.net/browse/WEBRTC-640)
---
This PR adds the client type and client version to the call invitation in order to allow for SDK metric tracking by platform. 
No client type or version was included in the call invitation
Now the call invitation includes an Android platform value that cannot be changed, as well as a version taken from the BuildConfig of the Gradle Build version. 
1. Launch sample application
2. Create call
3. monitor logcat and see new invitation JSON message.
> [WEBRTC-640] Set an SDK property on INVITE (include client type and version in user-agent field)

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/DialogParams.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/ParamRequest.kt
[WebRTC-640 -  Set an SDK property on INVITE (include client type and version in user-agent field).](https://telnyx.atlassian.net/browse/WEBRTC-640)
---
This PR adds the client type and client version to the call invitation in order to allow for SDK metric tracking by platform. These states are represented in a single User-Agent variable
No client type or version was included in the call invitation
Now the call invitation includes an Android platform value that cannot be changed, as well as a version is taken from the BuildConfig of the Gradle Build version. These values are both available in User-Agent
1. Launch sample application
2. Create call
3. monitor logcat and see new invitation JSON message.
> [WEBRTC-640] Change type and version to single user agent

- app/src/androidTest/java/com/telnyx/webrtc/sdk/ui/MainActivityTest.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Config.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Peer.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/TxServerConfiguration.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/socket/TxSocketTest.kt
[WebRTC-665 - Provide a hidden way to switch to DEV ENV for testing.](https://telnyx.atlassian.net/browse/WEBRTC-665)
---
This PR implements a method of switching to DEV and PROD environments within the application. DEV environment requires a VPN so exposing these details is not an issue. 
The environment is changed via long pressing the Telnyx logo. An alert dialog will appear providing options to switch to Dev, Prod and copy the firebase token instance
A few minor changes were required to enable this, but nothing will break current customer implementations. There is now a TxServerConfiguration class that has default values that can be included in connect(), however, there is a default configuration provided so it is not an issue if the customer does not include one. 
Other changes …
> [WEBRTC-665] Provide a hidden way to switch to DEV ENV for testing.

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-680 - Run client-ready method in coroutine scope .](https://telnyx.atlassian.net/browse/WEBRTC-680)
---
We will now receive client-ready after a successful login too.
> [WEBRTC-680] Run client ready method in coroutine scope 

- app/src/androidTest/java/com/telnyx/webrtc/sdk/ui/MainActivityTest.kt
- app/src/main/java/com/telnyx/webrtc/sdk/utility/MyFirebaseMessagingService.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/ParamRequest.kt
[WebRTC-681 - Fix Login message parameters for Push Notifications](https://telnyx.atlassian.net/browse/WEBRTC-681)
---
This PR fixes the login message for both token and credential login messages. The PN token and provider are now provided via User Variables and not params as they were before. 
This change makes these values readable to our backend where they were previously not being caught 
PN token and Provider being sent in params{}
PN token and Provider being sent in UserVariables{}
1. Login and confirm that parameters are now in the UserVariables section instead of params.
> [WEBRTC-681] Fix Login message parameters for Push Notifications

- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Peer.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocketListener.kt
[WebRTC-690 - Push Notification investigation.](https://telnyx.atlassian.net/browse/WEBRTC-690)
---
This PR fixes the autologin mechanism by storing the environment used after a successful login. 
There is also another socket listener method that is used to set our sessionID earlier, this makes it possible to build a call before the login is successful which is useful for the upcoming Push Notification release
We no longer send video media constraints on the WebRTC SDK
We now wait 300 ms before sending our invite, this means that we have time to gather more (most often all), ice candidates, before sending our invitation. This hopefully fixes a customer issue where IPv6 was the only candidate available, which is not supported
Environment not remembered for autologin
Session ID being set on …
> [WEBRTC-690][ENGDESK-11170] Push Notification investigation enhancements + IceCandidate Bug Fix

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxConfig.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocketListener.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
[WebRTC-711 - Fix REGISTRATION issue from ld6/sy1 in Telnyx WebRTC SDK.](https://telnyx.atlassian.net/browse/WEBRTC-711)
---
This PR implements a boolean value `autoRetry` to our login methods that will automatically try reconnect and log into our socket connection up to 3 times if set to true in the instance of receiving a FAIL_WAIT response from the gateway.
This is a temporary workaround to tackle the 480 SIP error we are receiving as a result of invalid gateway registrations
Tests are adjusted and added. 
FAIL_WAIT message would simply return an error. Often customers would then try login again without reconnecting to the socket, which would cause issues. (480 SIP error).
If `autoRetry` is set to true, we will automatically disconnect and reconnect to the socket and attempt the login …
> [WEBRTC-711] Fix REGISTRATION issue from ld6/sy1 in Telnyx WebRTC SDK

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/peer/Peer.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
[WebRTC-1417 - Dispose of PeerConnection and factory after a call.](https://telnyx.atlassian.net/browse/WEBRTC-1417)
---
This PR implements a few changes in order to get multiple subsequent calls working on Android 9 and below (for real devices rather than inside our sample application or web dialer). For whatever reason, this issue only occurs when calling a real device's number, not an application using the SDK. 
The issue appears to be with disposing PeerConnections and PeerConnectionFactories after they are used. Before we would simple create a new Peer object which held these variables and assign it to the same peerConnection variable within the call class.
For whatever reason, in Android 9 and below, this was not enough to clear microphone priority held by WebRtcAudioManager, so if …
> [WEBRTC-1417] Dispose of PeerConnection and factory after a call

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
[WebRTC-1618 - onRingingReceived missing leg and session ID fix ](https://telnyx.atlassian.net/browse/WEBRTC-1618)
---
This PR adds random UUID for the onRingingReceived Call message when the telnyx_session_id and telnyx_leg_id are missing from the jsonObject. 
If these params are missing (rare, uncertain of cause. Backend related), the application would crash
Instead of not handling the missing params, we now generate a random UUID. The call still works with these random values. 
1. Do call flow as normal
> [WEBRTC-1618] Generate random UUID when params are missing

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-2081 - Release MediaPlayer when stopped.](https://telnyx.atlassian.net/browse/WEBRTC-2081)
---
This PR includes some code changes to release MediaPlayer when stopped, then recreated when required again. 
This comes as a result of a customer reported issue, stating:
"app acquires a partial wake lock by calling acquire() with the PARTIAL_WAKE_LOCK flag. A partial wake lock becomes stuck if it is held for a long time while your app is running in the background (no part of your app is visible to the user). This information is the suggestion that Google returned to our APP. After I checked the corresponding code, I found this situation, so I asked your opinion on this. This is the document address given by Google : https://developer.android/. com/topic/performance/vitals/wakelock"
We …
> fix(WEBRTC-2081): Release MediaPlayer when stopped

- app/src/main/java/com/telnyx/webrtc/sdk/manager/UserManager.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/CallState.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/CauseCode.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/SocketMethod.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocketListener.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/receive/ReceivedResult.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/ParamRequest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/CallTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
[WebRTC-2102 - implement reconnect functionality with attach flow.](https://telnyx.atlassian.net/browse/WEBRTC-2102)
---
This PR implements the attach flow so that calls can be reconnected when network drops. 
When network drops, the SDK needs to reconnect to a socket and log in. When this is done an Attach message will be received on the websocket, this can be responded to in the same fashion as a call invitation (creating a Peer Connection, adding ice candidates, sending a reply socket message etc).
The mechanism for the reconnection always existed (see line 121 in TelnyxClient), however, we were not receiving an attach message because a sessid param was not being included in the login message -- we were sending sessionId instead.
Because of this, this PR also replaces all instances of …
> feat(WEBRTC-2102): implement reconnect functionality with attach flow

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-Clevio -  Call State is Connecting on Caller side whilst call is Active](https://telnyx.atlassian.net/jira/software/c/projects/TELAPPS/boards/98?modal=detail&selectedIssue=TELAPPS-4455&assignee=712020%3Ab1a9b25a-52c8-40d6-b13e-e80d50ca5db6)
---
Call state is connecting during active calls on the callers side. 
1. Call state is Active for all active calls.
2. Ringing state is post to the UI as well, when there's a valid incoming or outgoing call, for either caller or callee
1. Tested using the SDK in an implementing application
> Is/bug fix/call state fix for caller

- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
[WebRTC-Native Crash on Android When ending a Call not yet Ringing/(Ending calls in quick succession) - Ticket Description.](https://telnyx.atlassian.net/jira/software/c/projects/TELAPPS/boards/98?modal=detail&selectedIssue=TELAPPS-4488&assignee=712020%3Ab1a9b25a-52c8-40d6-b13e-e80d50ca5db6)
---
Dispose off Peer_connection after every endCall
1. End call does not produce the `nativeClose` Crash
> Native Crash on Android When ending a Call not yet Ringing/(Ending calls in quick succession)

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-2355 - Ticket Description.](https://telnyx.atlassian.net/browse/WEBRTC-2355)
> Remove Unwanted IPS from SDP

- xmlapp/build.gradle
- xmlapp/src/main/java/org/telnyx/webrtc/xmlapp/MainActivity.kt
- xmlapp/src/main/java/org/telnyx/webrtc/xmlapp/login/LoginBottomSheetFragment.kt
- xmlapp/src/main/java/org/telnyx/webrtc/xmlapp/login/LoginFragment.kt
- xmlapp/src/main/res/layout/activity_main.xml
- xmlapp/src/main/res/navigation/nav_graph.xml
This PR migrates the xmlapp module to use ViewBinding, improving type safety and reducing boilerplate code.
- Enable ViewBinding in xmlapp module
- Update MainActivity to use ViewBinding and navigation
- Convert LoginFragment to use ViewBinding
- Convert LoginBottomSheetFragment to use ViewBinding and proper bottom sheet behavior
- Set up navigation between fragments
- Add click listeners and basic UI interactions
Jira: [WEBRTC-2459](https://telnyx.atlassian.net/browse/WEBRTC-2459)
[WEBRTC-2459]: https://telnyx.atlassian.net/browse/WEBRTC-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2459: Migrate xmlapp to ViewBinding

- README.md
- docs-markdown/push-notification/app-setup.md
- docs-markdown/push-notification/troubleshooting.md
This PR adds a comprehensive troubleshooting guide for Android push notifications in the WebRTC SDK.
- Added a new troubleshooting.md file in the docs-markdown/push-notification/ directory
- The guide covers common points of failure:
- FCM Token not passed to login
- Incorrect google-services.json configuration
- Wrong push credential assigned to SIP Credential
- Incorrect push credential
- Login method limitations
- Added additional troubleshooting steps and a "Still Having Issues?" section
- [WEBRTC-2524](https://telnyx.atlassian.net/browse/WEBRTC-2524)
[WEBRTC-2524]: https://telnyx.atlassian.net/browse/WEBRTC-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2524: [Android] Trouble Shooting Push Notification Section

- xml_app/build.gradle.kts
- xml_app/google-services.json
- xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
This PR fixes the crash in the XML demo app that occurs during login due to uninitialized Firebase.
- Added Firebase initialization in MainActivity
- Added initProfile call in a coroutine, similar to how it is done in the compose_app module
The app was crashing with IllegalStateException because FirebaseApp was not initialized before accessing FirebaseMessaging.getInstance().
1. Launch the XML demo app
2. Attempt to log in
3. Verify that the app no longer crashes
Fixes WEBRTC-2538
> WEBRTC-2538: Fix XML demo app crash during login

- compose_app/src/main/java/org/telnyx/webrtc/compose_app/MainActivity.kt
- telnyx_rtc/CHANGELOG.md
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxConfig.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/peer/Peer.kt
Implements a timeout mechanism for reconnection attempts in the telnyx_rtc module.
- Added RECONNECT_TIMEOUT constant (60 seconds)
- Implemented reconnection timer to track duration
- Added timeout handling in network callback methods
- Created setReconnectionTimeout method in Call class
- Added proper error handling and user notification
Manually tested by simulating network changes and verifying that calls are properly terminated after 60 seconds of reconnection attempts.
https://github.com/user-attachments/assets/b695eba7-fbbd-4723-a496-a4df0f7274cb
[WEBRTC-2546](https://telnyx.atlassian.net/browse/WEBRTC-2546)
[WEBRTC-2546]: https://telnyx.atlassian.net/browse/WEBRTC-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2546: Android - Adding reconnection time out

- docs-markdown/error-handling/ErrorHandling.md
This PR adds comprehensive documentation on error handling in the Android SDK, as requested in [ENGDESK-39136](https://telnyx.atlassian.net/browse/ENGDESK-39136).
- Created a new directory `docs-markdown/error-handling`
- Added `ErrorHandling.md` with detailed documentation on:
- Error handling architecture
- Error scenarios (Gateway Registration, WebSocket Errors, Network Issues)
- Code examples
- Best practices
- Common error scenarios and solutions
- [ENGDESK-39136](https://telnyx.atlassian.net/browse/ENGDESK-39136)
[ENGDESK-39136]: https://telnyx.atlassian.net/browse/ENGDESK-39136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENGDESK-39136]: https://telnyx.atlassian.net/browse/ENGDESK-39136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> ENGDESK-39136: Create documentation on error handling in SDK

- samples/compose_app/build.gradle.kts
- samples/compose_app/src/main/AndroidManifest.xml
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/MainActivity.kt
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/LoginBottomSheet.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/AnswerIncomingPushCall.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/CallNotificationService.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/MyFirebaseMessagingService.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/NotificationsService.kt
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/SocketError.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/peer/Peer.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
[WebRTC-2368 - PSTN call answer from push not connecting.](https://telnyx.atlassian.net/browse/WEBRTC-2368)
---
Some changes recently made seem to affect our ability to answer PSTN calls from push
- Using NOHOST transport type
- Not properly handling codec error (call would stay on)
- always showing disconnect button
- no full screen pending intent for push notifications to handle when no action is pressed
- Still manually skipping local ice candidates, but no longer using NOHOST transport type
- Call will end on client side when we receive codec error to avoid confusion
- Only show disconnect / connect button while on a call
- full screen pending intent for push notification when no action is pressed allowing user to reply when app is connected
- Bump WebRTC library version
1. Test …
> PSTN call answer from push not connecting

- samples/compose_app/src/main/res/values/colors.xml
- samples/compose_app/src/main/res/values/themes.xml
- samples/xml_app/src/main/res/values/colors.xml
- samples/xml_app/src/main/res/values/themes.xml
This PR changes the splash screen background color to #00E3AA for both the compose_app and xml_app modules as requested in [WEBRTC-2591](https://telnyx.atlassian.net/browse/WEBRTC-2591).
- Added/updated the telnyx_green color to #00E3AA in both modules' color resources
- Added Android 12+ splash screen configuration to both modules' theme files using the android:windowSplashScreenBackground attribute
- Verified that the splash screen background color is set to the specified green color (#00E3AA) for both the compose_app and xml_app modules.
- [WEBRTC-2591](https://telnyx.atlassian.net/browse/WEBRTC-2591)
[WEBRTC-2591]: https://telnyx.atlassian.net/browse/WEBRTC-2591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEBRTC-2591]: …
> WEBRTC-2591: [Android] Splash Screen UI Change

- samples/xml_app/src/main/AndroidManifest.xml
- telnyx_common/src/main/java/com/telnyx/webrtc/common/service/CallForegroundService.kt
---
xml_app was not successfully registering the call foreground service, meaning that when the app was in the background audio would stop after a period of time - killed by the OS. 
Root cause was a missing registration of the service in the Android Manifest
- Registration of service missing in AndroidManifest
- Regisered service in Android Manifest
1. Launch the xml_app and receive a call
2. Background the app
3. Chat for 30 seconds plus and make sure audio still flows.
> Fix: CallForegroundService not registered for xml_app sample

- README.md
- telnyx_rtc/proguard-rules.pro
This PR updates the Proguard rules for the Android SDK.
- Removed reference to org.webrtc in README.md as it's no longer used
- Added Kotlin experimental warnings to proguard-rules.pro:
- -dontwarn kotlin.Experimental$Level
- -dontwarn kotlin.Experimental
- -dontwarn kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher
- Updated README.md with the new Proguard rules
[WEBRTC-2661](https://telnyx.atlassian.net/browse/WEBRTC-2661)
[WEBRTC-2661]: https://telnyx.atlassian.net/browse/WEBRTC-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2661: Android SDK Proguard rules description

- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
This PR fixes the issue where the loading dialog would remain visible indefinitely when a login error occurs (e.g., incorrect password).
- Updated the `handleError` method in `TelnyxViewModel` to set `_isLoading.value = false` when an error occurs, ensuring the loading dialog is dismissed.
[WEBRTC-2677](https://telnyx.atlassian.net/browse/WEBRTC-2677)
[WEBRTC-2677]: https://telnyx.atlassian.net/browse/WEBRTC-2677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2677: Fix infinite loading dialog on login error

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[ENGDESK-41158 - Connection not Recovered After Network Lost.](https://telnyx.atlassian.net/browse/ENGDESK-41158)
---
Issue 
When during outgoing call the network connection is lost and then it back, call won't be reconnected.
Solution
When the app is receiving onClientReady we need to keep voice_sdk_id and use it during another connection.
Steps to test:
- make outgoing call
- turn off network and turn on it again
- the active call should be reconnected
> Saving voice_sdk_id after connection

- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
This PR addresses the issue described in [WEBRTC-2676](https://telnyx.atlassian.net/browse/WEBRTC-2676).
- Modified the  function in  to set sessionState as Disconnected not only when currentCall is null but also when currentCall state is Error.
- This ensures the app navigates back to the login/connect screen after reconnection timeout.
- Verified that the app correctly navigates to the login/connect screen when a call is dropped due to network issues.
- [WEBRTC-2674](https://telnyx.atlassian.net/browse/WEBRTC-2674)
[WEBRTC-2676]: https://telnyx.atlassian.net/browse/WEBRTC-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEBRTC-2674]: https://telnyx.atlassian.net/browse/WEBRTC-2674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> WEBRTC-2676: [Android] Navigate to login / connect screen and clear call states after DROPPED

- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
This PR fixes an issue where the Android app was not disconnecting properly after rejecting a push notification, causing the next call to come on the socket if the app was minimized.
- Changed  to  in the  function in TelnyxViewModel.kt
[WEBRTC-2678](https://telnyx.atlassian.net/browse/WEBRTC-2678)
[WEBRTC-2678]: https://telnyx.atlassian.net/browse/WEBRTC-2678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2678: [Android] App not disconnecting after rejecting push notification so next call comes on socket if minimized

- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/authentication/AuthenticateByToken.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/AnswerIncomingPushCall.kt
This PR implements autologin for token when reacting to push credential.
- Modified the AnswerIncomingPushCall class to use TokenConfig when sipToken is not null in the user profile
- Falls back to CredentialConfig when sipToken is null
[WEBRTC-2675](https://telnyx.atlassian.net/browse/WEBRTC-2675)
- Verified that the code correctly checks for the presence of sipToken and uses the appropriate configuration
[WEBRTC-2675]: https://telnyx.atlassian.net/browse/WEBRTC-2675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2675: [Android] Autologin for token when reacting to push credential

- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
[WebRTC-2697 - Push Notification call reject failed.](https://telnyx.atlassian.net/browse/WEBRTC-2697)
---
Steps to reproduce the wrong state:
log in to the app
move app to the background
lock the screen
make incoming call
choose Reject option
After above steps the app will stuck in loading screen and call won’t be rejected.
> Fix: Push Notification call reject failed

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/stats/WebRTCReporter.kt
[WebRTC-2698 - Debug Stats are created when call metrics is enabled.](https://telnyx.atlassian.net/browse/WEBRTC-2698)
---
Steps to reproduce:
- enable call metrics
- disable config stats
- after the call debug stats will be created
> Webrtc 2698 - Fix: Debug Stats are created when call metrics is enabled

- docs-markdown/classes/Call.md
- docs-markdown/classes/TelnyxClient.md
- docs-markdown/error-handling/ErrorHandling.md
- docs-markdown/quickstart/Quickstart.md
- docs-markdown/socket/ReceivedMessageBody.md
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- samples/connection_service_app/src/main/java/com/telnyx/webrtc/sdk/utility/telecom/call/TelecomCallManager.kt
- samples/connection_service_app/src/main/java/com/telnyx/webrtc/sdk/utility/telecom/call/TelecomCallScreen.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxCommon.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/AnswerIncomingPushCall.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/RejectIncomingPushCall.kt
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/CallState.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/SocketError.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocketListener.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/stats/WebRTCReporter.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/receive/ReceivedResult.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/receive/SocketResponse.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/CallTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
- versions.gradle
---
This pull request introduces significant enhancements to call state reporting and error handling within the Android WebRTC SDK. The primary goal is to provide developers with more granular information about call lifecycle events, particularly for call drops, reconnections, and terminations, including specific error codes. This allows for more informative UI/UX in client applications and better diagnostic capabilities.
Key changes include:
-   Refactoring `CallState` to a `sealed class` to allow states to carry associated data.
-   Introducing `CallNetworkChangeReason` to specify reasons for `DROPPED` and `RECONNECTING` states (e.g., network loss, network switch).
-   Introducing `CallTerminationReason` to provide detailed cause, SIP codes, and reasons when a call transitions to the …
> WebRTC-2701 - Enhance Call State and Termination Reason Reporting in SDK

- samples/compose_app/src/androidTest/java/org/telnyx/webrtc/compose_app/MainActivityTest.kt
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/LoginBottomSheet.kt
[WebRTC-2722 - flakey UI tests on compose.](https://telnyx.atlassian.net/browse/WEBRTC-2722)
---
- UI tests failing both locally and remotely 
Adjust UI tests in MainActivityTest.kt so that assertion failures do not occur
1. Run tests locally and ensure they pass
2. Ideally they pass on this PR as well (Remote via Firebase Test Labs)
> Fix: flakey UI tests on compose

- README.md
- docs-markdown/classes/Call.md
- docs-markdown/classes/TelnyxClient.md
- samples/connection_service_app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/receive/SocketObserver.kt
This PR updates the SocketObserver onError method signature to include an errorCode parameter as requested in WEBRTC-2733.
- **SocketObserver.kt**: Updated the abstract  method signature from  to 
- **SocketObserver.kt**: Updated the  method to pass  to the  callback
- **MainActivity.kt**: Updated the sample implementation to handle the new errorCode parameter
The SocketResponse class already had an  field, so this change simply exposes it through the SocketObserver interface. The errorCode parameter is nullable to maintain compatibility and handle cases where no error code is available.
- Updated the sample app implementation in MainActivity to log both errorCode and message
- All existing functionality remains intact as the errorCode parameter is optional (nullable)
- Jira Ticket: …
> WEBRTC-2733: SocketObserver onError method signature change

- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/CallScreen.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/HomeCallFragment.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
[WebRTC-2770 - Fix broken Client Side Push handling.](https://telnyx.atlassian.net/browse/WEBRTC-2770)
---
In case of push call the order of incoming messages had been changed. This lead to the situation in which client app, after answering or rejecting incoming push call, stuck in 'loading' state.
Now incoming push call will properly shown in compose and xml demo apps.
> Fix broken Client Side Push handling

- README.md
- docs-markdown/push-notification/app-setup.md
- docs-markdown/push-notification/quickstart.md
[WEBRTC-2799 - Android Decline Push Documentation Update](https://telnyx.atlassian.net/browse/WEBRTC-2799)
---
This PR updates the Android WebRTC SDK documentation to reflect the new simplified push notification decline functionality introduced in PR #561.
**Complex Push Decline Flow:**
- User taps decline on notification
- App launches via PendingIntent
- App connects to socket
- App waits for invite message
- App manually sends bye message to decline
- App remains open
**Documentation Issues:**
- No documentation of the new BackgroundCallDeclineService
- Missing information about the simplified decline flow
- Outdated examples showing complex implementation
**Simplified Push Decline Flow:**
- User taps decline on notification
- BackgroundCallDeclineService starts automatically
- Service …
> [WEBRTC-2799] - Android Decline Push Documentation Update

- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/LoginBottomSheet.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/login/LoginBottomSheetFragment.kt
- samples/xml_app/src/main/res/layout/credentials_layout.xml
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/authentication/AuthenticateBySIPCredentials.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/authentication/AuthenticateByToken.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/model/Profile.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/util/Utils.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Config.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxConfig.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/peer/Peer.kt
This PR implements the `forceRelayCandidate` parameter in the Android WebRTC SDK to match the iOS implementation. When enabled, this parameter forces the WebRTC connection to use TURN relay servers exclusively, which can improve connectivity in restrictive network environments.
- **Jira Ticket**: [WEBRTC-2804](https://telnyx.atlassian.net/browse/WEBRTC-2804)
- **Description**: Investigate Force Relay Config parameter for Android SDK
- **TelnyxConfig.kt**: Added `forceRelayCandidate` parameter to both `CredentialConfig` and `TokenConfig` classes (default: false)
- **Peer.kt**: Modified constructor to accept `forceRelayCandidate` parameter and updated `buildPeerConnection()` to set `iceTransportsType = RELAY` when enabled
- **TelnyxClient.kt**: Added helper function …
> [WEBRTC-2804] Implement forceRelayCandidate parameter in Android WebRTC SDK

- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/BackgroundCallDeclineService.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-2886 - Fix: every second decline of push call doesn't work.](https://telnyx.atlassian.net/browse/WEBRTC-2886)
---
Reason:
When the app is decline or answer incoming push call it needs to use voice_sdk_id from incoming push notification. The app was keeping this value from previous push call and use it again, instead to use new received value.
Steps to reproduce:
- make push call
- decline
- repeat how many time do you want
- each call should be properly declined
> WEBRTC-2886 Fix: every second decline of push call doesn't work

- .llm-repo-instructions
- samples/connection_service_app/src/main/java/com/telnyx/webrtc/sdk/utility/telecom/call/TelecomCallManager.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxCommon.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/call/SendInvite.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/model/AudioCodec.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/AudioCodec.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/send/DialogParams.kt
This PR implements preferred codec functionality for the Android WebRTC SDK as requested in [WEBRTC-2904](https://telnyx.atlassian.net/browse/WEBRTC-2904).
- **AudioCodec Data Class**: Added new AudioCodec model in telnyx_common module with fields for channels, clockRate, mimeType, and sdpFmtpLine
- **getSupportedAudioCodecs() Method**: Implemented in TelnyxClient using Android's MediaCodecList to detect device audio codec capabilities
- **CallDialogParams Update**: Added preferredCodecs field with proper JSON serialization support
- **newInvite() Method Enhancement**: Updated method signature to accept optional preferredCodecs parameter
- **SendInvite Class**: Updated to support preferred codecs parameter
- **TelnyxCommon**: Added convenience method for getting supported codecs
- …
> [WEBRTC-2904] Implement preferred codec functionality for Android WebRTC SDK

- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/CallScreen.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/HomeCallFragment.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
[WebRTC-2941 - Fix: missing caller name on push call](https://telnyx.atlassian.net/browse/WEBRTC-2941)
---
In case of incoming push call, caller name is not visible in 'Sip Number' field, in both sample apps.
Steps to reproduce:
- make incoming push call
- answer the call
- field 'Sip Number' will be empty
> WEBRTC-2941 Fix: missing caller name on push call

- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/login/LoginBottomSheetFragment.kt
[WebRTC-2944 - [Android] Fix: refresh user profiles list after update](https://telnyx.atlassian.net/browse/WEBRTC-2944)
---
In sample apps, when user will update some profile parameters and then use it to call, old parameters will be still taken during connection.
> WEBRTC-2944 Fix: profile doesn't refresh after update
