- .github/workflows/firebase_test_lab.yml
> [WEBRTC-644] No longer need dokka generation

- README.md
[WebRTC-743 - Update README docs.](https://telnyx.atlassian.net/browse/WEBRTC-743)
---
Readme update to include most recent changes and Push Notification reference. 
Outdated instructions, no push notification reference
See above
N/A
> [WEBRTC-743] Update README docs

- app/build.gradle
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- build.gradle
- telnyx_rtc/build.gradle
[WebRTC-745 - dependency version bumps.](https://telnyx.atlassian.net/browse/WEBRTC-745)
---
Does what it says on the tin....
> [WEBRTC-745] dependency version bumps

- .github/workflows/firebase_test_lab.yml
- app/build.gradle
- build.gradle
- telnyx_rtc/build.gradle
[WebRTC-749 - Dependency bumps (actions / gradle).](https://telnyx.atlassian.net/browse/WEBRTC-749)
---
Dependency bumps
> [WEBRTC-749] Dependency bumps (actions / gradle)

- .idea/misc.xml
- jitpack.yml
- telnyx_rtc/build.gradle
Jitpack release fix
JAVA version bump. 
Quick PR.
> [WEBRTC-755] Jitpack release fix, JAVA version bump

- README.md
Quick PR
Reference Jetpack Compose Sample application
> [WEBRTC-756] Reference Jetpack Compose Sample

- .github/workflows/firebase_test_lab.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- .github/workflows/scheduled_unit_test.yml
- .github/workflows/unit_test_on_push.yml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- telnyx_rtc/build.gradle
[WebRTC-2078 - dependabot bumps.](https://telnyx.atlassian.net/browse/WEBRTC-2078)
---
Dependabot bumps. Done in one PR so as to test all of them before merging to avoid any issues that can occur by auto-merging the dependabot PRs
> chore(WEBRTC-2078): dependabot bumps

- .github/workflows/firebase_test_lab.yml
- .github/workflows/release.yml
- .github/workflows/scheduled_unit_test.yml
- .github/workflows/unit_test_on_push.yml
- app/build.gradle
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- build.gradle
- telnyx_rtc/build.gradle
- versions.gradle
[WebRTC-2141 - dependency bumps](https://telnyx.atlassian.net/browse/WEBRTC-2141)
---
This is a simple chore PR to update dependencies recommended by dependabot. In the past auto-merging these PRs untested has caused issues. 
This PR updates all listed dependencies and have been tested locally. 
Outdated dependencies flagged by dependabot
Updated dependencies and tested locally to ensure no issues 
1. Launch and use app as usual
2. Run local tests as usual
> chore(WEBRTC-2141): dependency bumps

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/socket/TxSocketTest.kt
Disconnect issue fixed
added notification permission for android 13
> Disconnect callback issue fixed

- app/build.gradle
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/peer/Peer.kt
Removed WebRTC library org.webrtc:google-webrtc
Added WebRTC Library io.getstream:stream-webrtc-android
> change webrtc library.

- README.md
- app/src/main/java/com/telnyx/webrtc/sdk/ui/CallInstanceFragment.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/SocketStatus.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocketListener.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/receive/SocketObserver.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/verto/receive/SocketResponse.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/TelnyxClientTest.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/socket/TxSocketTest.kt
Add dedicated function for disconnect call back
> Add dedicated function for disconnect callback

- telnyx_rtc/build.gradle
[WEBRTC-24707 - Ticket title](https://telnyx.atlassian.net/browse/ENGDESK-24707)
---
Reconnect Socket and Login when connection is Lost
- Reconnection was not possible
- Socket will try to reconnect after connection is lost
> Re-establish Socket Connection Impl

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
[WebRTC-2269](https://telnyx.atlassian.net/browse/WEBRTC-2269)
> Fix SSL Error on Android 8.1

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-2258](https://telnyx.atlassian.net/browse/WEBRTC-2258)
Voice SDK ID Reconnection
> Reconnect Socket to Voice SDK ID

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[ENGDESK-36849- Ticket Description.](https://telnyx.atlassian.net/browse/ENGDESK-36849)
Fix for SDP missing STUN or TURN Candidates
Inblound or Ourbound Call works
> Fix for SDP missing STUN or TURN Candidates

- docs-markdown/push-notification/app-setup.md
- docs-markdown/push-notification/portal-setup.md
[WEBRTC-2384](https://telnyx.atlassian.net/browse/WEBRTC-2384)
---
Add Push Notification DOcs
[WEBRTC-2384]: https://telnyx.atlassian.net/browse/WEBRTC-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Push Notification Docs

- build.gradle
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/AndroidManifest.xml
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/utilities/ConnectivityHelper.kt
- versions.gradle
[ENGDESK-38001 - Remove bugsnag.](https://telnyx.atlassian.net/browse/ENGDESK-38001)
---
- BugSnag implemented
- BugSnag removed as no longer required
1. Launch app and make sure it runs as expected
> Remove BugSnag implementation from SDK and App

- telnyx_rtc/CHANGELOG.md
- telnyx_rtc/build.gradle
- BugSnag Removal
- Debug Stats implementation
> SDK Release 1.4.4

- app/src/main/java/com/telnyx/webrtc/sdk/ui/CallInstanceFragment.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/model/CallState.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/stats/WebRTCReporter.kt
- telnyx_rtc/src/test/java/com/telnyx/webrtc/sdk/CallTest.kt
2. Implement new CallStates for call recovery
[WebRTC-2495](https://telnyx.atlassian.net/browse/WEBRTC-2495)
---
1. Implement new CallStates for Call Recovery
2. Fix Crash when WebRTC Stats is Enabled for NetworkSwitch 
https://github.com/user-attachments/assets/1df281cc-6f9e-4ad6-ae62-30930cd06506
>  NetworkSwitch Fixes

- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainActivity.kt
- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/Call.kt
- xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/HomeCallFragment.kt
- xml_app/src/main/res/layout/activity_main.xml
[WebRTC-2532 - Add CallState to HomeScreen while on call .](https://telnyx.atlassian.net/browse/WEBRTC-2532)
---
- No Call state present while on a call
- Current Call call state present while on a call 
1. Launch app
2. Join call
3. See State
> Add CallState to HomeScreen while on call 

- app/src/main/java/com/telnyx/webrtc/sdk/ui/MainViewModel.kt
- compose_app/src/main/java/org/telnyx/webrtc/compose_app/MainActivity.kt
- compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/CallScreen.kt
- compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- compose_app/src/main/res/values/strings.xml
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/authentication/AuthenticateBySIPCredentials.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/authentication/AuthenticateByToken.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- xml_app/src/main/res/layout/bottom_sheet_environment.xml
- xml_app/src/main/res/values/strings.xml
Implements long press functionality on the Telnyx logo to show a bottom sheet with environment options in both compose_app and xml_app.
- Added long press gesture to Telnyx logo in both compose_app and xml_app
- Created bottom sheet with environment options:
* Development Environment
* Production Environment
* Copy FCM Token
* Disable Push Notifications
- Set up placeholder methods for functionality implementation
- The actual functionality for each option needs to be implemented
- The UI components and interactions are ready for use
Jira: [WEBRTC-2533](https://telnyx.atlassian.net/browse/WEBRTC-2533)
[WEBRTC-2533]: https://telnyx.atlassian.net/browse/WEBRTC-2533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEBRTC-2533: [Android] Disable Push Notifications + Copy FCM Token

- compose_app/build.gradle.kts
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/call/RejectCall.kt
[WebRTC-2535 - Reject call.](https://telnyx.atlassian.net/browse/WEBRTC-2535)
---
Fix reject call
Could not reject call
Can now reject incoming call as well as end existing call 
1. Receive call
2. Reject
> fix: reject call as well as end existing call

- .github/workflows/ui_tests.yml
- compose_app/build.gradle.kts
- compose_app/src/androidTest/java/org/telnyx/webrtc/compose_app/MainActivityTest.kt
- compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/CallScreen.kt
- compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/viewcomponents/Text.kt
- xml_app/build.gradle.kts
- xml_app/src/androidTest/java/org/telnyx/webrtc/xmlapp/MainActivityTest.kt
[WEBRTC-2467 - UI Test & Regression Testing](https://telnyx.atlassian.net/browse/WEBRTC-2467)
UI tests added in both: compose and xml demo apps.
Added GitHub action which runs UI tests in Firebase Lab.
> WEBRTC-2467 UI Test & Regression Testing

- docs-markdown/quickstart/Quickstart.md
- telnyx_common/README.md
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
This PR adds documentation for the Telnyx Common module as requested in [WEBRTC-2563](https://telnyx.atlassian.net/browse/WEBRTC-2563).
1. Added a comprehensive README.md to the telnyx_common module explaining:
- Module purpose and overview
- Integration instructions
- Key components (TelnyxViewModel, CallForegroundService, Notification system)
- Implementation examples
- Best practices and troubleshooting
2. Added detailed documentation comments to the TelnyxViewModel.kt file:
- Class-level documentation
- Documentation for all public methods
- Parameter descriptions
- Return value descriptions
3. Created a Quickstart.md in the docs-markdown/quickstart directory with the same content as the README.md
These changes will help developers understand how to use the telnyx_common module as a …
> WEBRTC-2563: [Docs] Telnyx Common module

- docs-markdown/push-notification/quickstart.md
- samples/compose_app/src/main/AndroidManifest.xml
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/MainActivity.kt
- samples/xml_app/src/main/AndroidManifest.xml
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/CallNotificationReceiver.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/CallNotificationService.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/LegacyCallNotificationService.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/notification/MyFirebaseMessagingService.kt
This PR adds a new quickstart.md document to the push-notification documentation directory. The document provides information about using the telnyx_common module's notification implementation in Android applications.
The documentation covers:
- Overview of the telnyx_common notification components
- Detailed explanation of each notification class (CallNotificationService, CallNotificationReceiver, MyFirebaseMessagingService, NotificationsService)
- Integration steps for using these components
- References to the sample apps (Compose and XML)
- Best practices and troubleshooting tips
[WEBRTC-2564](https://telnyx.atlassian.net/browse/WEBRTC-2564)
[WEBRTC-2564]: https://telnyx.atlassian.net/browse/WEBRTC-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> WEBRTC-2564: [Docs] Push Notification documentation update - mention telnyx_common

- telnyx_rtc/CHANGELOG.md
- telnyx_rtc/build.gradle
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/peer/Peer.kt
[ENGDESK-40134- Adjust ICE Candidate Requirements before sending Answer Response ](https://telnyx.atlassian.net/browse/ENGDESK-40134)
---
The flow is now:
1. Start the ICE candidate-gathering process
2. For each new valid candidate:
3. Update the candidate count
4. Reset the negotiation timer
5. If no new candidates arrive for 300ms we consider the negotiation complete
7. Send the answer with whatever candidates we have
1. Test via push notification call being received and answer
> Adjust ICE Candidate Requirements before sending Answer Response

- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/AnswerIncomingPushCall.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/RejectIncomingPushCall.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/socket/TxSocket.kt
[WEBRTC-2703](https://telnyx.atlassian.net/browse/WEBRTC-2703)
---
- Fix `push Login` for accept and reject Call
- Fix Default Call State as (Done)
- Handle Call Failed Errors
[WEBRTC-2703]: https://telnyx.atlassian.net/browse/WEBRTC-2703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> - Fix Push Login Errors

- docs-markdown/webrtc-stats/WebRtcStats.md
[WEBRTC-2694](https://telnyx.atlassian.net/browse/WEBRTC-2694)
Added Webrtc Stats Docs 
[WEBRTC-2694]: https://telnyx.atlassian.net/browse/WEBRTC-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> - Add WebRtcStats.md

- README.md
- docs-markdown/config/TelnyxConfig.md
[WebRTC-2751 - Update README and developer's docs by new SDK variables.](https://telnyx.atlassian.net/browse/WEBRTC-2751)
---
Updated TelnyxConfig.md and README.md by description of new parameters.
> Update README and developer's docs by new SDK variables

- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
[WebRTC-2848 - State error and crash after Phone Number call to SIP Connection.](https://telnyx.atlassian.net/browse/WEBRTC-2848)
---
In TelnyxClient we are using WebRTCReporter object to collect debug data. There was only one instance of this class, so when the app did two parallel calls one object was lost. When second call was ended, WebRTCReporter object wasn't stopped and were trying to collect debug data from already destroyed Peer and this leads to the crash.
Steps to reproduce:
- make a call, use Call History
- when you will choose one of the Call History items, there will be a short gap when you will be able to press Call button
- this will leads to make 2 parallel calls
- end first call and wait couple of seconds
- when the Socket will receive BYE message for the second call, …
> WEBRTC-2848: [FIX] State error and crash after Phone Number call to SIP Connection

- samples/compose_app/build.gradle.kts
- samples/compose_app/src/androidTest/java/org/telnyx/webrtc/compose_app/MainActivityTest.kt
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/components/CodecSelectionDialog.kt
- samples/compose_app/src/main/java/org/telnyx/webrtc/compose_app/ui/screens/HomeScreen.kt
- samples/compose_app/src/main/res/values/strings.xml
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/MainActivity.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/AvailableCodecsAdapter.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/AvailableCodecsFragment.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/CodecSelectionDialogFragment.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/SelectedCodecsAdapter.kt
- samples/xml_app/src/main/java/org/telnyx/webrtc/xml_app/home/SelectedCodecsFragment.kt
- samples/xml_app/src/main/res/layout/dialog_codec_selection.xml
- samples/xml_app/src/main/res/layout/dialog_codec_selection_tabbed.xml
- samples/xml_app/src/main/res/layout/fragment_available_codecs.xml
- samples/xml_app/src/main/res/layout/fragment_selected_codecs.xml
- samples/xml_app/src/main/res/layout/item_available_codec.xml
- samples/xml_app/src/main/res/layout/item_selected_codec.xml
- samples/xml_app/src/main/res/menu/overflow_menu.xml
- samples/xml_app/src/main/res/values/strings.xml
- telnyx_common/src/main/java/com/telnyx/webrtc/common/TelnyxViewModel.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/call/AcceptCall.kt
- telnyx_common/src/main/java/com/telnyx/webrtc/common/domain/push/AnswerIncomingPushCall.kt
- telnyx_rtc/src/main/java/com/telnyx/webrtc/sdk/TelnyxClient.kt
This PR implements a preferred codec dialog picker for the Android WebRTC SDK, allowing users to select and reorder their preferred audio codecs for calls.
[WEBRTC-2929](https://telnyx.atlassian.net/browse/WEBRTC-2929)
- **TelnyxClient**: Extended  method to support  parameter
- **TelnyxViewModel**: Added  property with  and  methods
- **AcceptCall Domain**: Updated to include  parameter and propagate through call chain
- **sendInvite**: Updated to use stored preferred codecs as fallback
- **CodecSelectionDialog**: New component with drag-to-reorder functionality using reorderable library
- **HomeScreen**: Integrated codec selection into overflow menu
- **Material 3 Design**: Proper theming and visual feedback with toast notifications
- **Dependencies**: Added reorderable library for …
> WEBRTC-2929: [Android] Preferred Codec Dialog Picker

- README.md
- docs-markdown/ai-agent/anonymous-login.md
- docs-markdown/ai-agent/introduction.md
- docs-markdown/ai-agent/starting-conversations.md
- docs-markdown/ai-agent/text-messaging.md
- docs-markdown/ai-agent/transcript-updates.md
This PR adds comprehensive documentation for Android AI Agent SDK methods based on PR #625 implementation, following the Flutter SDK format from PR #194.
- Added complete table of contents for better navigation
- Added AI Agent usage section with 4-step implementation guide:
1. **Anonymous Login**: Connect to AI assistants without SIP credentials using `anonymousLogin()`
2. **Starting Conversations**: Initiate calls with `newInvite()` (destination ignored after anonymous login)
3. **Transcript Updates**: Real-time conversation transcripts via `transcriptUpdateFlow`
4. **Text Messaging**: Send text messages during calls with `sendAIAssistantMessage()`
Created detailed documentation in `docs-markdown/ai-agent/`:
- **introduction.md** - Overview, quick start, and key features
- …
> [WEBRTC-2948] - Android Mobile AI Agent SDK Method Readme + Documentation

- push-notification-tool/package-lock.json
- push-notification-tool/package.json
- push-notification-tool/push-sender.js
[WebRTC-2974 - Update Axios in push-notification-tool to newest version.](https://telnyx.atlassian.net/browse/WEBRTC-2974)
---
Axios version updated to 1.12.2 and set max data size to avoid DoS attack
> WEBRTC-2974: Update Axios in push-notification-tool to newest version
